version: '2'
services:
  mysql:
        image: mysql:8.0
        container_name: mysql-server-80
        command: --default-authentication-plugin=mysql_native_password
        working_dir: /application
        volumes:
          - .:/application
        environment:
          - MYSQL_ROOT_PASSWORD=.123456*
          - MYSQL_DATABASE=aula_irroba
          - MYSQL_USER=irroba
          - MYSQL_PASSWORD=abc123456*
        ports:
          - "8082:3306"
  website:
    container_name: php72
    build:
      context: ./
    links:
      - "mysql:database"
    volumes:
      - ./src:/var/www/html
    ports:
      - 8500:80
    depends_on:
      - mysql
